import {calculate} from './solver.js';
const state={targetN:'20',targetP:'20',targetK:'20',targetWeight:'100',fertilizers:[{name:'Urê (46-0-0)',n:46,p:0,k:0,isSelected:true},{name:'DAP (18-46-0)',n:18,p:46,k:0,isSelected:true},{name:'Kali clorua KCl (0-0-60)',n:0,p:0,k:60,isSelected:true},{name:'SA (21-0-0)',n:21,p:0,k:0,isSelected:false},{name:'Super lân (0-16-0)',n:0,p:16,k:0,isSelected:false}],results:[]};
const app=document.querySelector('#app'),back=document.querySelector('#back'),title=document.querySelector('#page-title');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=s=>{const v=Number(String(s).trim());return Number.isNaN(v)?0:v;};
const fmt=n=>n.toLocaleString('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2});
function field(id,label,value=''){return `<label class="field" for="${id}">${label}<input id="${id}" name="${id}" inputmode="decimal" value="${esc(value)}" autocomplete="off"></label>`;}
function navigate(page){location.hash=page;}
function checks(){document.querySelector('#fertilizers').innerHTML=state.fertilizers.map((f,i)=>`<label class="check"><input type="checkbox" data-index="${i}" ${f.isSelected?'checked':''}><span>${esc(f.name)}<small class="fertilizer-details">Đạm (N): ${esc(f.n)}% · Lân (P₂O₅): ${esc(f.p)}% · Kali (K₂O): ${esc(f.k)}%</small></span></label>`).join('');}
function run(){const parsed=key=>num(state[key].replaceAll(',','.'));state.results=calculate({targetN:Math.max(0,Math.min(100,parsed('targetN'))),targetP:Math.max(0,Math.min(100,parsed('targetP'))),targetK:Math.max(0,Math.min(100,parsed('targetK'))),targetWeight:Math.max(0,parsed('targetWeight')),selectedFertilizers:state.fertilizers});if(!document.querySelector('#inline-results')){history.replaceState(null,'','#input');render();}renderResults();document.querySelector('#inline-results').scrollIntoView({behavior:'smooth',block:'start'});return state.results;}
function render(){if(location.hash!=='#input')history.replaceState(null,'','#input');back.hidden=true;title.textContent='Tính phối trộn NPK';
 {app.innerHTML=`<h1>Tính phối trộn NPK</h1><div class="input-grid"><div><section class="panel"><h2>Tỷ lệ phân muốn trộn (%)</h2><div class="triple">${field('targetN','N (Ure)',state.targetN)}${field('targetP','P₂O₅ (Lân)',state.targetP)}${field('targetK','K₂O (Kali)',state.targetK)}</div><h2 class="space">Khối lượng muốn trộn (kg)</h2>${field('targetWeight','Khối lượng (kg)',state.targetWeight)}</section><section class="panel"><h2>Các loại phân hiện có</h2><div id="fertilizers"></div></section></div><div><form id="add-form" class="panel"><h2>Thêm loại phân</h2><label class="field" for="newName">Tên phân<input id="newName" autocomplete="off"></label><div class="triple space">${field('newN','%N')}${field('newP','%P')}${field('newK','%K')}</div><button class="primary add" type="submit">＋ Nhập</button></form><button class="primary" id="calculate">TÍNH PHỐI TRỘN</button></div></div><section id="inline-results" aria-live="polite" hidden></section>`;checks();['targetN','targetP','targetK','targetWeight'].forEach(k=>document.getElementById(k).oninput=e=>state[k]=e.target.value);document.querySelector('#fertilizers').onchange=e=>{if(e.target.dataset.index!==undefined)state.fertilizers[Number(e.target.dataset.index)].isSelected=e.target.checked;};document.querySelector('#add-form').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#newName').value,n=num(document.querySelector('#newN').value),p=num(document.querySelector('#newP').value),k=num(document.querySelector('#newK').value);if(name.length&&n+p+k<=100){state.fertilizers.push({name,n,p,k,isSelected:true});checks();e.target.reset();}};document.querySelector('#calculate').onclick=run;renderResults();}

 window.scrollTo(0,0);
}
function renderResults(){const output=document.querySelector('#inline-results');if(!output)return;output.hidden=!state.results.length;output.innerHTML='<h2>Kết quả phối trộn</h2>';if(!state.results.length){output.insertAdjacentHTML('beforeend','<p class="muted">Không có kết quả. Vui lòng kiểm tra lại đầu vào và nhấn “TÍNH PHỐI TRỘN”.</p>');return;}output.insertAdjacentHTML('beforeend',`<div class="results">${state.results.map(r=>`<section class="result"><h2>${esc(r.description==='LỖI'?'THÔNG BÁO':r.description)}</h2><div class="row"><span>Tổng khối lượng:</span><strong>${fmt(r.totalWeight)} kg</strong></div><div class="row"><span>Chất độn (Filler):</span><strong>${fmt(r.filler)} kg</strong></div><p class="grade">Công thức đạt:<span class="grade-values"><span>N ${fmt(r.actualNPK[0])}%</span><span>P₂O₅ ${fmt(r.actualNPK[1])}%</span><span>K₂O ${fmt(r.actualNPK[2])}%</span></span></p>${r.isFormulaValid&&r.components.length?`<div class="ingredients"><strong>Bảng nguyên liệu:</strong>${r.components.map(([name,w])=>`<div class="row"><span>${esc(name)}</span><strong>${fmt(w)} kg</strong></div>`).join('')}</div>`:''}${r.smartNote?`<p class="note ${!r.isFormulaValid||r.isOverflow||r.isDistorted||r.smartNote.includes('chưa phù hợp')?'warning':''}">${esc(r.smartNote)}</p>`:''}</section>`).join('')}</div>`);const [a,b]=state.results;if(a?.isFormulaValid&&b?.isFormulaValid&&a.components.length&&b.components.length){const diff=a.components.reduce((s,c)=>s+c[1],0)-b.components.reduce((s,c)=>s+c[1],0);output.insertAdjacentHTML('beforeend',`<section class="economic"><h2>SO SÁNH KINH TẾ</h2><p>${Math.abs(diff)<.01?'Cả hai phương án sử dụng cùng một lượng phân đơn.':`Phương án ${diff>0?'2':'1'} tiết kiệm hơn, sử dụng ít hơn ${fmt(Math.abs(diff))} kg phân đơn so với Phương án ${diff>0?'1':'2'}.`}</p><small>Lời khuyên: Nên chọn phương án có tổng lượng phân đơn thấp hơn để giảm chi phí vận chuyển và bón phân.</small></section>`);}}
window.addEventListener('hashchange',render);render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'calculate_npk_mix',description:'Tính phối trộn từ dữ liệu và nguyên liệu đang chọn, hiển thị kết quả.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{const results=run();return {results};}})).catch(()=>{});}catch{}}
